# Generated by Django 6.0.3 on 2026-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
