# Generated by Django 6.0.3 on 2026-03-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_users_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phonenumber',
        ),
    ]
