# Generated by Django 6.0.3 on 2026-04-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_role'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0006_rename_o_created_at_order_created_at_and_more'),
        ('products', '0006_rename_p_brand_products_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='CustomUsers',
        ),
    ]
