# Generated by Django 6.0.3 on 2026-03-28 05:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_price', models.IntegerField()),
                ('p_brand', models.CharField(max_length=100)),
                ('p_type', models.CharField(max_length=100)),
                ('p_description', models.CharField(max_length=200)),
                ('p_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
