# Generated by Django 6.0.3 on 2026-04-01 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_w_product_wishlist_w_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='w_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='w_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
