# Generated by Django 6.0.3 on 2026-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_p_brand_products_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
