# Generated by Django 6.0.3 on 2026-04-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
