# Generated by Django 6.0.3 on 2026-04-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description',
        ),
    ]
