# Generated by Django 6.0.3 on 2026-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallettransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
