# Generated by Django 6.0.3 on 2026-03-31 06:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_rename_w_product_wishlist_w_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_created_at', models.DateField(auto_now_add=True)),
                ('p_paymet_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('p_payment_method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('upi', 'UPI')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='enter a valid pin number', regex='^\\d{6}$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='enter a valid phone number ', regex='^\\+?\\d{10}$')])),
                ('p_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('p_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
