# Generated by Django 6.0.3 on 2026-03-31 07:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('products', '0005_rename_w_product_wishlist_w_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='p_product',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='payments',
            name='p_payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('onlinepayment', 'OnlinePayment')], max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid pincode number', regex='^\\d{6}$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{10}$')])),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_quantity', models.IntegerField(default=1)),
                ('o_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order')),
            ],
        ),
    ]
