# Generated by Django 6.0.3 on 2026-03-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payments_address_remove_payments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.order'),
        ),
    ]
