# Generated by Django 6.0.3 on 2026-04-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='p_paymet_status',
            new_name='p_payment_status',
        ),
    ]
