# Generated by Django 6.0.3 on 2026-04-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_p_paymet_status_payments_p_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='o_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='o_total_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='o_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='o_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='o_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='o_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='p_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='p_payment_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='p_payment_status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='p_total_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='p_user',
            new_name='user',
        ),
    ]
