# Generated by Django 6.0.3 on 2026-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_o_created_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('onlinepayment', 'OnlinePayment'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
