# Generated by Django 6.0.3 on 2026-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payments_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
    ]
