# Generated by Django 6.0.3 on 2026-04-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payments_refund_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='refund_processed',
        ),
    ]
